"""Create tables

Revision ID: d422e31bdf96
Revises: 
Create Date: 2025-12-12 17:08:17.100606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd422e31bdf96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('specialization_code', sa.String(length=16), nullable=False),
    sa.Column('specialization_title', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'course', 'specialization_code', name='uc_stream')
    )
    op.create_table('student_group',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_type', sa.Enum('ЛЕКЦИЯ', 'ПРАКТИКА', 'НЕИЗВЕСТНО', name='sessiontype'), server_default='НЕИЗВЕСТНО', nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('group_code', sa.String(length=8), nullable=False),
    sa.Column('stream_id', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['group_code'], ['student_group.code'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'start_time', 'group_code', 'stream_id', name='uc_class_session')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'ru'"), nullable=False),
    sa.Column('group_code', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_code'], ['student_group.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('lesson')
    op.drop_table('student_group')
    op.drop_table('stream')
    # ### end Alembic commands ###
